# Site settings
title: NSKostas
email: nskostas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A personal website currently in construction, made with Jekyll
  and Github Pages. Thanks for visiting.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nskostas.com" # the base hostname & protocol for your site
twitter_username: nskostas
github_username:  nskostas

# Build settings
markdown: kramdown
